<?php

/**
 * Initialize the custom theme options.
 */
add_action('init', 'custom_theme_options');

/**
 * Build the custom settings & update OptionTree.
 */
function custom_theme_options() {

    // OptionTree is not loaded yet, or this is not an admin request.
    if (!function_exists('ot_settings_id') || !is_admin()) {
        return false;
    }

    // Get a copy of the saved settings array.
    $saved_settings = get_option(ot_settings_id(), array());

    // Custom settings array that will eventually be passes to the OptionTree Settings API Class.
    $custom_settings = array(
        'contextual_help' => array(
            'sidebar' => esc_html__('<p>Sidebar content goes here!</p>', 'coach'),
        ),
        'sections' => array(
            array(
                'id' => 'home_page_banner',
                'title' => esc_html__('Home Page Banner', 'coach'),
            ),
            array(
                'id' => 'home_page_success_stories',
                'title' => esc_html__('Home Page Success Stories', 'coach'),
            ),
            array(
                'id' => 'home_page_what_clients_say',
                'title' => esc_html__('Home Page What Clients Say', 'coach'),
            ),
            array(
                'id' => 'home_page_my_work_process',
                'title' => esc_html__('Home Page My Work Process', 'coach'),
            ),
            array(
                'id' => 'home_page_how_can_i_help',
                'title' => esc_html__('Home Page How Can I Help', 'coach'),
            ),
            array(
                'id' => 'home_page_grow_up_your_business',
                'title' => esc_html__('Home Page Grow Up Your Business', 'coach'),
            ),
            array(
                'id' => 'footer_sections',
                'title' => esc_html__('Footer Sections', 'coach'),
            ),
        ),
        'settings' => array(
            array(
                'id' => 'home_page_banner_title',
                'label' => esc_html__('Home Page  Banner Title', 'coach'),
                'desc' => esc_html__('Add Home Page Banner Title here', 'coach'),
                'std' => '',
                'type' => 'textarea',
                'section' => 'home_page_banner',
                'rows' => '2',
                'post_type' => 'post,page',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_banner_subtitle',
                'label' => esc_html__('Home Page Banner Subtitle', 'coach'),
                'desc' => esc_html__('Enter the subtitle to be appeared in Home page banner subtitle', 'coach'),
                'std' => '',
                'type' => 'textarea',
                'section' => 'home_page_banner',
                'rows' => '1',
                'post_type' => 'post,page',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_banner_button_link',
                'label' => esc_html__('Home Page Banner Button Link', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'page-select',
                'section' => 'home_page_banner',
                'rows' => '1',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_banner_button_text',
                'label' => esc_html__('Home Page Banner Button Text', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'home_page_banner',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_banner_image',
                'label' => esc_html__('Home Page Banner Image', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'background',
                'section' => 'home_page_banner',
                'rows' => '',
                'post_type' => 'post,page',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_success_stories_title',
                'label' => esc_html__('Home Page Success Stories Title', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'textarea-simple',
                'section' => 'home_page_success_stories',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_success_stories_description',
                'label' => esc_html__('Home page Success Stories Description', 'coach'),
                'desc' => esc_html__('Add Success stories description text here', 'coach'),
                'std' => '',
                'type' => 'textarea',
                'section' => 'home_page_success_stories',
                'rows' => '3',
                'post_type' => 'post,page',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_success_stories_service_1',
                'label' => esc_html__('Home page Success Stories Service 1', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'custom-post-type-select',
                'section' => 'home_page_success_stories',
                'rows' => '',
                'post_type' => 'services',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_success_stories_service_2',
                'label' => esc_html__('Home page Success Stories Service 2', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'custom-post-type-select',
                'section' => 'home_page_success_stories',
                'rows' => '',
                'post_type' => 'services',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_success_stories_service_3',
                'label' => esc_html__('Home page Success Stories Service 3', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'custom-post-type-select',
                'section' => 'home_page_success_stories',
                'rows' => '',
                'post_type' => 'services',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_what_clients_say_title',
                'label' => esc_html__('Home Page What Clients Say Title', 'coach'),
                'desc' => esc_html__('What clients say Section Heading', 'coach'),
                'std' => '',
                'type' => 'textarea',
                'section' => 'home_page_what_clients_say',
                'rows' => '1',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_what_clients_say_content',
                'label' => esc_html__('Home Page What Clients Say Content', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'textarea',
                'section' => 'home_page_what_clients_say',
                'rows' => '3',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_what_clients_say_name',
                'label' => esc_html__('Home Page What Clients Say Name', 'coach'),
                'desc' => esc_html__('Name of the client whos testimonial is added in content area', 'coach'),
                'std' => '',
                'type' => 'text',
                'section' => 'home_page_what_clients_say',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_what_clients_say_background_image',
                'label' => esc_html__('Home Page What Clients Say Background Image', 'coach'),
                'desc' => esc_html__('Add Background Image', 'coach'),
                'std' => '',
                'type' => 'upload',
                'section' => 'home_page_what_clients_say',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_my_work_process_title',
                'label' => esc_html__('Home Page My Work Process Title', 'coach'),
                'desc' => esc_html__('Add Title of the section', 'coach'),
                'std' => '',
                'type' => 'textarea',
                'section' => 'home_page_my_work_process',
                'rows' => '1',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_my_work_process_description',
                'label' => esc_html__('Home Page My Work Process Description', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'textarea',
                'section' => 'home_page_my_work_process',
                'rows' => '3',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_my_work_process_features',
                'label' => esc_html__('Home Page My Work Process Features', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'list-item',
                'section' => 'home_page_my_work_process',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_my_work_background_image',
                'label' => esc_html__('Home Page My Work Background Image', 'coach'),
                'desc' => esc_html__('Add sections Background Image', 'coach'),
                'std' => '',
                'type' => 'background',
                'section' => 'home_page_my_work_process',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_my_work_button_text',
                'label' => esc_html__('Home Page My Work Button Text', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'home_page_my_work_process',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_my_work_process_button_link',
                'label' => esc_html__('Home Page My Work Process Button Link', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'page-select',
                'section' => 'home_page_my_work_process',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_how_can_i_help_title',
                'label' => esc_html__('Home Page How Can I Help Title', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'textarea-simple',
                'section' => 'home_page_how_can_i_help',
                'rows' => '1',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_how_can_i_help_description',
                'label' => esc_html__('Home Page How Can I Help Description', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'textarea',
                'section' => 'home_page_how_can_i_help',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_how_can_i_help_button_text',
                'label' => esc_html__('Home Page How Can I Help Button Text', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'home_page_how_can_i_help',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_how_can_i_help_button_link',
                'label' => esc_html__('Home Page How Can I Help Button Link', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'page-select',
                'section' => 'home_page_how_can_i_help',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_how_can_we_help_background_',
                'label' => esc_html__('Home Page How Can We Help Background ', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'background',
                'section' => 'home_page_how_can_i_help',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_grow_up_your_business_title',
                'label' => esc_html__('Home Page Grow Up Your Business Title', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'textarea-simple',
                'section' => 'home_page_grow_up_your_business',
                'rows' => '2',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'home_page_grow_up_your_business_description',
                'label' => esc_html__('Home Page Grow Up Your Business Description', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'textarea',
                'section' => 'home_page_grow_up_your_business',
                'rows' => '4',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'footer_section_one',
                'label' => esc_html__('Footer Section One', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'textarea',
                'section' => 'footer_sections',
                'rows' => '4',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'footer_section_two',
                'label' => esc_html__('Footer Section Two', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'textarea',
                'section' => 'footer_sections',
                'rows' => '6',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'footer_section_three',
                'label' => esc_html__('Footer Section Three', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'textarea',
                'section' => 'footer_sections',
                'rows' => '6',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
            array(
                'id' => 'footer_copyright_section',
                'label' => esc_html__('Footer Copyright Section', 'coach'),
                'desc' => '',
                'std' => '',
                'type' => 'textarea',
                'section' => 'footer_sections',
                'rows' => '3',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
            ),
        )
    );

    // Allow settings to be filtered before saving.
    $custom_settings = apply_filters(ot_settings_id() . '_args', $custom_settings);

    // Settings are not the same update the DB.
    if ($saved_settings !== $custom_settings) {
        update_option(ot_settings_id(), $custom_settings);
    }

    // Lets OptionTree know the UI Builder is being overridden.
    global $ot_has_custom_theme_options;
    $ot_has_custom_theme_options = true;
}
